// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBcFJnrL-lXkqJ1SAtEHhph96m_5yblrY0',
    appId: '1:186180075136:web:47d171b3975782657c3065',
    messagingSenderId: '186180075136',
    projectId: 'medimind-781cc',
    authDomain: 'medimind-781cc.firebaseapp.com',
    storageBucket: 'medimind-781cc.firebasestorage.app',
    measurementId: 'G-HJT0HN6F9X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAWODb3s91uP5vFER79lOOOwJG4MwAHX74',
    appId: '1:186180075136:android:ca708e4e0af0f26f7c3065',
    messagingSenderId: '186180075136',
    projectId: 'medimind-781cc',
    storageBucket: 'medimind-781cc.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBIyy-JMeC-pn3QwsfjLrMpAb-FgQdxMgw',
    appId: '1:186180075136:ios:a03ec444821dd3a37c3065',
    messagingSenderId: '186180075136',
    projectId: 'medimind-781cc',
    storageBucket: 'medimind-781cc.firebasestorage.app',
    iosBundleId: 'com.example.medimind',
  );
}
